### ISSUE TITLE
Issue with rail ejectors

### ISSUE THREAD

**Issue by Sniper10231** [ckcz123/DSP_Battle#39]
when using rail ejectors to send solar sails into orbit it wont launch and instead just sit there and never shoot. So far ive only seen this error in saves that have started before the mod was installed.

Error:
![image](https://user-images.githubusercontent.com/26172823/159144299-8eac6e1e-e0bd-4ae4-92b1-65543e77df0b.png)
after removing the rail ejectors the errors would stop but placing them back down would make them unable to fire again and errors would continue again.

**Comment by ckcz123** [comment]
Are you using a mod that has stars > 100?

**Comment by Sniper10231** [comment]
I have just tested with another save and there are no errors with 64 stars

**Comment by ckcz123** [comment]
This is fixed by 1.1.0. Please update your mod version.

**Comment by Sniper10231** [comment]
thank you for the help
