### ISSUE TITLE
Missile silo malfunction

### ISSUE THREAD

**Issue by Cacilia-11** [ckcz123/DSP_Battle#46]
I have many mods installed and I get an error.
Even if I turn off everything but the VOIDMOD, I still get the error.
Some mods are not able to be turned off due to time acceleration in the reproduction environment
Sorry if the problem is my environment.
The error is not launching the missile.
Error count continues to increase while timing to fire.
![2022-05-06_09h33_16](https://user-images.githubusercontent.com/93427665/167053908-cd55de68-dbc1-4241-b71b-c4869e930674.png)
.

**Comment by Cacilia-11** [comment]
I tried the same mod configuration with different conditions.
Multiple planets in a star system (one star system) causes an error.
The error occurred when the number of planets in the system was 30.
No error when the number of planets in the system is 3.

**Comment by Cacilia-11** [comment]
恒星系に10の惑星でもエラーが起きた
母星に衛星が３つ　うち２つにミサイルサイロ
マイルストーンのロケット打ち上げは解除されたが
ミサイルは１つも発射されていない
マイルストーンのミサイル軌道表記は"#0-000"

**Comment by Cacilia-11** [comment]
Missiles fired from satellites of planets seem to cause errors
Tested with 10 planets in a star system
No error when launching missiles from the home planet
Missile launched from satellites 1 and 2 of the home star

**Comment by Cacilia-11** [comment]
I experimented with past saved data as well.
For 10 planets, no error if there is a missile silo on the planet.
For 30 planets, the error occurred even if only the home planet was used.

**Comment by ckcz123** [comment]
Hi Cacilia, yes, we only check the first 10 planets. See
https://github.com/ckcz123/DSP_Battle/blob/2.0/src/EnemyShips.cs#L137

**Comment by ckcz123** [comment]
We recommend not using such mod to have a star system with planets > 10.

**Comment by akdude2000** [comment]
would there be a way to change the number of planets checked?
