### ISSUE TITLE
Add a "How to Play" or "Using the mod" section to this readme and the mod page?

### ISSUE THREAD

**Issue by sjacobflaherty** [ckcz123/DSP_Battle#56]
https://github.com/ckcz123/DSP_Battle/blob/41d9b77463d609b3e0f665b8e80db29c1d3c57a9/README.md?plain=1#L44

It would be nice to add a section on "Using the Mod" for English
Especially because many options and features are not explained clearly in the English Translation. It was hard for me to enjoy this incredible mod at first. I only hope to make it easier for English users.
Here is an example.....

## Using the Mod

They come when your first interstellar logistics station is placed. From then on, stronger and stronger waves will assault you about every 60 minutes. They will never stop. They will never end.

They may target any planet with an interstellar logistics station. Though the first few waves will be in one system and easily manageable, assuming it will stay that way will lead to demise. Luckily, notifications and after-battle reports will fill you in on where you need to focus your rebuilding efforts. More information on ai targeting, notifications, and other mechanics are available in-game.

They are going to be a challenge to EXPERIENCED players who have extensive knowledge of the game and a library of finely tuned production blueprints. Though different difficulty levels exist, even easy is not recommended for new players or experienced players that want a casual run.

So far, we haven't encountered any issues installing this mod mid-run.  Want time to develop your foothold and prepare before you watch your galaxy burn? Great! 
*Personal Opinion* for users who want a casual start but a challenge late-game, I recommend installing the mod when you either make your first white science or your dyson sphere reaches 4GW.

Do not remove this mod once installed or you risk breaking your save.

**Comment by ckcz123** [comment]
Added in V2.1.4.
