### ISSUE TITLE
Constant Wave without break

### ISSUE THREAD

**Issue by solar121** [ckcz123/DSP_Battle#69]
Is there a way to incress the gap between when one wave end and the next start? If not the can you add that  as a config or tie it to the difficulty.

**Comment by starfi5h** [comment]
![q1597531q](https://github.com/ckcz123/DSP_Battle/assets/50672801/c27b9a99-40b7-47d6-907f-585cd6373f54)
Enter 'q1597531q' can open the mod console.
The command `settime` can set the timer to the next wave attack.
